//
//  ZYProgressHUDConfig.h
//  XiangQinXiangAi
//
//  Created by ZYVincent on 12-3-22.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#define ZYPROGRESSGIFWIDTH 50
#define ZYPROGRESSGIFHEIGHT 50

#define ZYPROGRESS_MESSAGELABEL_FONT_SIZE 13

#define ZYPROGRESS_MESSAGELABEL_TEXTCOLOR_RED 70
#define ZYPROGRESS_MESSAGELABEL_TEXTCOLOR_BLUE 113
#define ZYPROGRESS_MESSAGELABEL_TEXTCOLOR_GREEN 60

#define ZYPROGRESSHUDPOSITION CGRectMake(ORGIN_X_FORVIEW,ORGIN_Y_FORVIEW,ZYPROGRESS_MESSAGELABEL_WIDTH+2*ZYPROGRESSGIFORGIN_X,ZYPROGRESSGIFWIDTH+ZYPROGRESS_MESSAGELABEL_HEIGHT+ZYPROGRESSGIFORGIN_Y)
